spring:
  application:
    name: spring-ai-kotlin-test
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      audio:
        transcription:
          options:
            model: whisper-1
            language: fr
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
        initialize-schema: true
        databaseName: "default"
        collectionName: "SpringAIKotlinTest"
rag-test:
  enabled: true
  documentsToLoad:
    - classpath:/rag/FT_ChauffeEau.pdf
    - https://www.thermor.fr/produits/radiateur-electrique